import img from '../images/pic__COLOR_pic.png'

export const movies = [
  {
    id: 1,
    nameRU: '33 слова о дизайне',
    image: img,
    duration: 120,
    trailerLink: "https://www.youtube.com/",
  },
  {
    id: 2,
    nameRU: 'В погоне за Бенкси',
    image: img,
    duration: 40,
    trailerLink: "https://www.youtube.com/",
  },
  {
    id: 3,
    nameRU: 'В погоне за Бенкси',
    image: img,
    duration: 40,
    trailerLink: "https://www.youtube.com/",
  },
  {
    id: 4,
    nameRU: 'В погоне за Бенкси',
    image: img,
    duration: 40,
    trailerLink: "https://www.youtube.com/",
  },
  {
    id: 5,
    nameRU: 'В погоне за Бенкси',
    image: img,
    duration: 40,
    trailerLink: "https://www.youtube.com/",
  },
  {
    id: 6,
    nameRU: 'В погоне за Бенкси',
    image: img,
    duration: 40,
    trailerLink: "https://www.youtube.com/",
  },
  {
    id: 7,
    nameRU: 'В погоне за Бенкси',
    image: img,
    duration: 40,
    trailerLink: "https://www.youtube.com/",
  },
  {
    id: 8,
    nameRU: 'В погоне за Бенкси',
    image: img,
    duration: 40,
    trailerLink: "https://www.youtube.com/",
  },
  {
    id: 9,
    nameRU: 'В погоне за Бенкси',
    image: img,
    duration: 40,
    trailerLink: "https://www.youtube.com/",
  },
  {
    id: 10,
    nameRU: 'В погоне за Бенкси',
    image: img,
    duration: 40,
    trailerLink: "https://www.youtube.com/",
  },
  {
    id: 11,
    nameRU: 'В погоне за Бенкси',
    image: img,
    duration: 40,
    trailerLink: "https://www.youtube.com/",
  },
  {
    id: 12,
    nameRU: 'В погоне за Бенкси',
    image: img,
    duration: 40,
    trailerLink: "https://www.youtube.com/",
  },
  {
    id: 13,
    nameRU: 'В погоне за Бенкси',
    image: img,
    duration: 40,
    trailerLink: "https://www.youtube.com/",
  },
  {
    id: 14,
    nameRU: 'В погоне за Бенкси',
    image: img,
    duration: 40,
    trailerLink: "https://www.youtube.com/",
  },
  {
    id: 15,
    nameRU: 'В погоне за Бенкси',
    image: img,
    duration: 40,
    trailerLink: "https://www.youtube.com/",
  },
  {
    id: 16,
    nameRU: 'В погоне за Бенкси',
    image: img,
    duration: 40,
    trailerLink: "https://www.youtube.com/",
  },
  {
    id: 17,
    nameRU: 'В погоне за Бенкси',
    image: img,
    duration: 40,
    trailerLink: "https://www.youtube.com/",
  },
  {
    id: 18,
    nameRU: 'В погоне за Бенкси',
    image: img,
    duration: 40,
    trailerLink: "https://www.youtube.com/",
  },
  {
    id: 19,
    nameRU: 'В погоне за Бенкси',
    image: img,
    duration: 40,
    trailerLink: "https://www.youtube.com/",
  },
  {
    id: 20,
    nameRU: 'В погоне за Бенкси',
    image: img,
    duration: 40,
    trailerLink: "https://www.youtube.com/",
  },
  {
    id: 21,
    nameRU: 'В погоне за Бенкси',
    image: img,
    duration: 40,
    trailerLink: "https://www.youtube.com/",
  },
  {
    id: 22,
    nameRU: 'В погоне за Бенкси',
    image: img,
    duration: 40,
    trailerLink: "https://www.youtube.com/",
  },
]